IDC_Manage/urls.py
from django.conf.urls import url, include
from xadmin.plugins import xversion
from django.views.generic.base import RedirectView
from IDC_Manage import views
from django.conf.urls.static import static
from django.conf import settings
import xadmin
import dc_info.urls


xadmin.autodiscover()
xversion.register_models()


urlpatterns = [
    url(r'^xadmin/', include(xadmin.site.urls)),
    url(r'^login/', views.Login.as_view(), name='login'),
    url(r'^logout', views.acc_logout, name='logout'),
    url(r'^favicon.ico$', RedirectView.as_view(url='/static/favicon.ico')),
    url(r'^', include(dc_info.urls, namespace='dcinfo'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = views.permission_denied
handler404 = views.page_no_found
handler500 = views.page_erro

dc_info/urls.py
from django.conf.urls import url
from dc_info.views import cabinet
from dc_info.views import equipment
from dc_info.views import index
from dc_info.views import inventory
from dc_info.views import user
from dc_info.views import abnormal
from dc_info.views import customer
from dc_info.views import export_info

urlpatterns = [
    url(r'^$', index.index, name='index'),  # 主页
    url(r'^userprofile/$', user.userprofile, name='userprofile'),  # 个人信息主页s

    url(r'^cabinet/(?P<dcname>.+)/(?P<idcname>.+)/create_cabinet/$',
        cabinet.create_cabinet, name='create_cabinet'),  # 添加机柜
    url(r'^cabinet/(?P<dcname>.+)/(?P<idcname>.+)/import_cabinet/$',
        cabinet.import_cabinet, name='import_cabinet'),  # 导入机柜
    url(r'^cabinet/(?P<dcname>.+)/(?P<idcname>.+)/$',
        cabinet.get_cabinet_info, name='get_cabinet'),  # 访问机柜信息
    url(r'^delete_cabinet/$', cabinet.delete_cabinet,
        name='delete_cabinet'),  # 删除机柜

    url(r'^customet_cabinet_log/$', cabinet.customet_cabinet_log,
        name='customer_cabinet_log'),  # 访问客户机柜操作日志视图

    url(r'^equipmen/(?P<dcname>.+)/(?P<idcname>.+)/(?P<equipment_id>\d+)/$',
        equipment.edit_equipment, name='edit_equipment'),  # 编辑设备信息
    url(r'^equipmen/(?P<dcname>.+)/(?P<idcname>.+)/create_equipment/$',
        equipment.create_equipment, name='create_equipment'),  # 增加设备信息
    url(r'^equipmen/(?P<dcname>.+)/(?P<idcname>.+)/import_equipment/$',
        equipment.import_equipment, name='import_equipment'),  # 批量导入设备信息
    url(r'^equipmen/(?P<dcname>.+)/(?P<idcname>.+)/$',
        equipment.get_equipmen_info, name='get_equipmen'),  # 访问设备信息
    url(r'^delete_equipment/$',
        equipment.delete_equipment,
        name='delete_qeuipment'),
    # 删除设备
    url(r'^selectinput/get_(?P<name>.+)/$',
        equipment.equipment_getinfo),  # 编辑设备时候获取信息

    url(r'^show_network_port/$', equipment.show_network_port,
        name='show_network_port'),  # 查看网络设备互联信息

    url(r'^customer_equipmen_log/$', equipment.customer_equipmen_log,
        name='customer_equipmen_log'),  # 访问客户设备操作体日志视图

    url(r'^inventory/(?P<dcname>.+)/(?P<idcname>.+)/edit_inventory/(?P<inventory_id>\d+)/$',
        inventory.edit_inventory, name='edit_inventory'),  # 编辑库存
    url(r'^inventory/(?P<dcname>.+)/(?P<idcname>.+)/import_inventory/$',
        inventory.bulk_import_inventory, name='import_inventory'),  # 批量导入库存
    url(r'^inventory/(?P<dcname>.+)/(?P<idcname>.+)/add_inventory/$',
        inventory.add_inventory, name='add_inventory'),  # 增加库存
    url(r'^inventory/(?P<dcname>.+)/(?P<idcname>.+)/$',
        inventory.get_inventory, name='inventory'),  # 库存管理
    url(r'^delete_inventory/$', inventory.delete_inventory,
        name='delete_inventory'),  # 删除库存信息
    url(r'^update_inventory_count/(?P<operation>\w+)/$',
        inventory.update_inventory_count),  # 增减库存数量

    url(r'^abnormal/(?P<dcname>.+)/(?P<idcname>.+)/$',
        abnormal.get_abnormal, name='get_abnormal'),  # 访问异常信息

    url(r'^customer/(?P<customet_name>.+)/$',
        view=customer.get_customer, name='get_customer'),  # 获取客户信息
    url(r'^ajax_cabinet_broken_line/$',
        index.ajax_cabinet_broken_line),  # 前端主页获取折线图数据
    url(r'^export_info/(?P<dcname>.+)/(?P<idcname>.+)/export_(?P<flag>cabinet|equipment|inventory)/$', view=export_info.export_info, name='export_info'),



]

dc_info/models.py
from django.utils.html import format_html
from django.db import models
from django.utils import timezone
from django.conf import settings

class DcInfo(models.Model):
    '''数据中心信息'''
    name = models.CharField(max_length=64, unique=True, verbose_name='数据中心名称')
    address = models.CharField(
        max_length=192,
        blank=True,
        null=True,
        verbose_name='数据中心地址')
    info = models.TextField(verbose_name='数据中心简介', blank=True, null=True)
    material = models.FileField(
        verbose_name='机房相关资料',
        blank=True,
        null=True,
        upload_to="%s/" %
        name)
    phon = models.CharField(max_length=64, verbose_name='机房值班电话')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'dcinfo'
        verbose_name = '数据中心'
        verbose_name_plural = '数据中心'


class IDCInfo(models.Model):
    '''机房信息'''
    dc = models.ForeignKey('DcInfo', verbose_name='所属数据中心')
    name = models.CharField(max_length=128, verbose_name='机房名称')
    info = models.TextField(verbose_name='机房简介', blank=True, null=True)
    principal = models.CharField(
        max_length=64,
        verbose_name='机房负责人',
        blank=True,
        null=True,
        editable=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'idcinfo'
        verbose_name = '机房信息'
        verbose_name_plural = '机房信息'
        unique_together = ('dc', 'name')


class Cabinet(models.Model):
    '''机柜信息'''
    idc = models.ForeignKey('IDCInfo', verbose_name='所属机房')
    number = models.CharField(max_length=64, verbose_name='机柜编号')
    customer = models.ForeignKey('Customer', verbose_name='所属客户')
    open_date = models.DateField(
        verbose_name='机柜开通日期',
        blank=True,
        null=True,
        default=timezone.now)

    def get_occupy(self):
        count = 0
        for i in self.equipmen_set.all():
            count += i.equipment_u
        return count

    def get_equipmen_count(self):
        return len(self.equipmen_set.all())

    def get_dc(self):
        return self.idc.dc

    get_dc.short_description = '数据中心'
    get_equipmen_count.short_description = "设备数量"
    get_occupy.short_description = '已占用U数'

    def __str__(self):
        return '%s-%s' % (self.idc, self.number)

    class Meta:
        unique_together = ('idc', 'number')
        db_table = 'cabinet'
        verbose_name_plural = '机柜信息'
        verbose_name = '机柜信息'


class Customer(models.Model):
    '''客户信息'''
    name = models.CharField(max_length=64, verbose_name='客户名称', unique=True)
    info = models.TextField(verbose_name='客户相关信息', blank=True, null=True)

    def get_cabinet_count(self):
        return self.cabinet_set.all().count()

    def get_equipment_count(self):
        return self.equipmen_set.all().count()

    get_cabinet_count.short_description = '机柜数量'
    get_equipment_count.short_description = '设备数量'

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'customer'
        verbose_name = '客户信息'
        verbose_name_plural = '客户信息'


class Equipmen(models.Model):
    '''设备信息'''
    cabinet = models.ForeignKey('Cabinet', verbose_name='所属机柜')
    equipment_type_choices = ((1, '服务器设备'), (2, '网络设备'))
    equipment_type = models.PositiveSmallIntegerField(
        choices=equipment_type_choices, verbose_name='设备类型')
    manufacturers = models.CharField(max_length=64, verbose_name='设备厂商')
    model_num = models.CharField(max_length=64, verbose_name='设备型号')
    serial_num = models.CharField(max_length=128, verbose_name='设备SN号')
    equipment_u = models.PositiveSmallIntegerField(verbose_name='设备U数')
    place_u = models.PositiveSmallIntegerField(
        verbose_name='所在机柜U数', blank=True, null=True)
    up_date = models.DateField(
        verbose_name='上架日期',
        blank=True,
        null=True)
    customer = models.ForeignKey('Customer', verbose_name='所属客户')
    node = models.TextField(verbose_name='设备信息描述', blank=True, null=True)

    def get_ip(self):
        # 获取设备IP地址
        if self.ipaddress_set.all():
            return self.ipaddress_set.all().first().ipaddre
        else:
            return '空'

    def get_mask(self):
        # 获取设备掩码
        if self.ipaddress_set.all():
            return self.ipaddress_set.all().first().netmask
        else:
            return '空'

    def get_gateway(self):
        # 获取设备网关
        if self.ipaddress_set.all():
            return self.ipaddress_set.all().first().gateway
        else:
            return '空'

    def get_dc(self):
        # 获取所属数据中心
        return self.cabinet.idc.dc.name

    get_ip.short_description = 'IP'
    get_mask.short_description = '掩码'
    get_gateway.short_description = '网关'
    get_dc.short_description = '数据中心'

    def __str__(self):
        return "%s-%s:%s" % (self.manufacturers,
                             self.model_num, self.serial_num)

    class Meta:
        unique_together = ('cabinet', 'serial_num')
        db_table = 'equipmen'
        verbose_name = '设备信息'
        verbose_name_plural = '设备信息'


class IpAddress(models.Model):
    '''IP地址细信息'''
    equipmen = models.ForeignKey('Equipmen', verbose_name='设备')
    ipaddre = models.GenericIPAddressField(
        protocol='IPV4', verbose_name='IP地址')
    netmask = models.GenericIPAddressField(
        protocol='IPV4', null=True, blank=True, verbose_name='子网掩码')
    gateway = models.GenericIPAddressField(
        protocol='IPV4', null=True, blank=True, verbose_name='网关地址')
    tags = models.CharField(
        max_length=64,
        verbose_name='IP标签',
        blank=True,
        null=True)

    def __str__(self):
        return '%s' % self.ipaddre

    class Meta:
        unique_together = ('equipmen', 'ipaddre')
        db_table = 'ipaddress'
        verbose_name = 'IPV4地址信息'
        verbose_name_plural = 'IPV4地址信息'


class PortInfo(models.Model):
    '''设备端口对应信息'''
    self_equipment = models.ForeignKey(
        'Equipmen',
        verbose_name="本端设备",
        related_name="self_equipment")
    self_equipment_port = models.CharField(max_length=32, verbose_name="本端端口号")
    up_equipment = models.ForeignKey(
        'Equipmen',
        verbose_name="上联设备",
        related_name="up_equipment")
    up_equipment_port = models.CharField(max_length=32, verbose_name="上联端口号")

    def __str__(self):
        return "%s : %s-%s : %s" % (self.self_equipment,
                                    self.self_equipment_port,
                                    self.up_equipment,
                                    self.up_equipment_port)

    class Meta:
        db_table = 'portinfo'
        verbose_name = "设备端口对应信息"
        verbose_name_plural = "设备端口对应信息"


class Inventory(models.Model):
    '''库存信息'''
    idc = models.ForeignKey('IDCInfo', verbose_name='所属机房')
    place = models.CharField(
        max_length=128,
        verbose_name='位置',
        blank=True,
        null=True)
    name = models.CharField(max_length=128, verbose_name='物品名称')
    name_num = models.CharField(max_length=128, verbose_name='物品型号')
    sn = models.CharField(
        max_length=128,
        verbose_name='SN号',
        blank=True,
        null=True)
    count = models.PositiveIntegerField(verbose_name='物品数量')
    customer = models.ForeignKey('Customer', verbose_name='所属客户')
    node = models.TextField(verbose_name='物品描述', blank=True, null=True)
    post_number = models.CharField(
        verbose_name='物流单号',
        blank=True,
        null=True,
        max_length=128)
    status_choices = ((0, '损坏'), (1, '完好'))
    status = models.PositiveSmallIntegerField(
        choices=status_choices, verbose_name='状态', default=1)

    def get_status(self):
        if self.status:
            return format_html('<span style="color: green;">完好</span>')
        else:
            return format_html('<span style="color: red;">损坏</span>')
    get_status.short_description = "状态"

    def __str__(self):
        return "%s-%s" % (self.idc, self.name)

    class Meta:
        db_table = 'inventory'
        verbose_name_plural = '库存信息'
        verbose_name = '库存信息'


class CabinetLog(models.Model):
    '机柜操作日志'
    handle_user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='操作用户')
    handle_type_choices = ((0, '关闭'), (1, '开通'),)
    handle_type = models.PositiveSmallIntegerField(
        choices=handle_type_choices, verbose_name='操作类型')
    date = models.DateField(verbose_name='日期')  # 机柜开关日期
    handle_date = models.DateTimeField(verbose_name='操作日期', auto_now_add=True)
    cabinet_dc = models.ForeignKey(DcInfo, verbose_name='机柜所属数据中心')
    cabinet_idc = models.ForeignKey('IDCInfo', verbose_name='所属机房')
    cabinet_number = models.CharField(max_length=64, verbose_name='机柜编号')
    customer = models.ForeignKey('Customer', verbose_name='所属客户')
    dc_surplus_count = models.IntegerField(verbose_name='数据中心剩余机柜数量')

    def get_handle_type(self):
        if self.handle_type == 0:
            return format_html('<span style="color: green;">关闭</span>')
        else:
            return format_html('<span style="color: red;">开通</span>')
    get_handle_type.short_description = "状态"

    def __str__(self):
        if self.handle_type == 0:
            return '%s%s%s-%s-%s' % (self.customer,
                                     '关闭',
                                     self.cabinet_dc,
                                     self.cabinet_idc,
                                     self.cabinet_number)
        else:
            return '%s%s%s-%s-%s' % (self.customer,
                                     '开通',
                                     self.cabinet_dc,
                                     self.cabinet_idc,
                                     self.cabinet_number)

    class Meta:
        db_table = 'cabinetlog'
        verbose_name = '机柜日志'
        verbose_name_plural = '机柜日志'


class EquipmenLog(models.Model):
    '''设备操作日志'''
    handle_user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='操作用户')
    handle_type_choices = ((0, '下架'), (1, '上架'),)

dc_info/views/abnormal.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from dc_info.views.commonality import CustomPaginator
from django.utils import timezone
from dc_info import models


# 前端获取异常信息数据统计页面
def get_abnormal(request, dcname, idcname):
    dc_obj = models.DcInfo.objects.all()
    customer_obj = models.Customer.objects.all()
    idc_obj = models.DcInfo.objects.get(
        name=dcname).idcinfo_set.filter(
        name=idcname)
    cabinet_obj = models.Cabinet.objects.filter(idc__in=idc_obj)  # 当前机房的所有机柜
    search_abnormal = request.GET.get('search_abnormal', None)  # 获取用户搜索的设备SN号
    current_page = request.GET.get('page', '1')  # 获取用户点击的页码
    schedule = request.GET.get('schedule', None)  # 获取过滤信息
    context = {
        "dc_obj": dc_obj,
        'customer_obj': customer_obj,
        'dcname': dcname,
        'idcname': idcname,
        'filter': {},
        'cabinet_obj': cabinet_obj}
    # 查询当前机房的所有异常告警信息
    abnormal_obj = models.AbnormalInfo.objects.filter(
        equipment__cabinet__idc__in=idc_obj).order_by('-find_time')
    # 点击确认处理按钮的时候传递的get
    handel_abnormal = request.GET.get('handel', None)
    # 点击确认处理按钮
    if handel_abnormal:
        models.AbnormalInfo.objects.filter(
            pk=int(handel_abnormal)).update(
            schedule=1, handel_time=timezone.now())
        return redirect('/abnormal/%s/%s/' % (dcname, idcname))

    if request.method == 'GET':
        # 当有所属异常设备SN
        if search_abnormal:
            abnormal_obj = abnormal_obj.filter(
                equipment__serial_num__icontains=search_abnormal.strip()).order_by('-find_time')
            context['filter']['search_abnormal'] = search_abnormal
        # 显示全部
        if schedule == 'all' or not schedule:
            abnormal_obj = abnormal_obj.order_by('-find_time')
        else:
            schedule = int(schedule)
            abnormal_obj = abnormal_obj.filter(
                schedule=schedule).order_by('find_time').reverse()
            context['filter']['schedule'] = schedule
    # post 增加异常告警信息
    if request.method == 'POST':
        equipment_id = request.POST.get('equipment_id')
        info = request.POST.get('info')
        schedule = request.POST.get('schedule')
        models.AbnormalInfo.objects.create(
            equipment_id=equipment_id,
            info=info,
            schedule=schedule,
            find_time=timezone.now())

    if current_page == 'all':
        paginator = CustomPaginator(1, 11, abnormal_obj, abnormal_obj.count())
    else:
        paginator = CustomPaginator(current_page, 11, abnormal_obj, 20)
    try:
        page_list = paginator.page(current_page)  # 分页
    except PageNotAnInteger:
        page_list = paginator.page(1)
    except EmptyPage:
        page_list = paginator.page(paginator.num_pages)
    context['page_list'] = page_list
    return render(request, 'dc_info/abnormal.html', context)

templates/dc_info/index.html
{% extends 'base_site.html' %}
{% load static %}
{% block title %}IDC资产管理系统-首页{% endblock title %}
{% block style %}
    <link rel="stylesheet" href="{% static 'dc_info/css/style.css' %}">
{% endblock style %}
{% block script %}
    <script src="{% static 'dc_info/js/index.js' %}"></script>
{% endblock script %}

{% block usermenu %}
    <li><a href="{% url 'dcinfo:userprofile' %}"><i class="lnr lnr-cog"></i> <span>Settings</span></a></li>
{% endblock usermenu %}



{% block menu_list %}
    {#    菜单部分#}
    <li><a href="{% url 'dcinfo:index' %}" class="active" id="showye"><i class="lnr lnr-home"></i> <span>首页</span></a>
    </li>
    <li>
        <a href="#subPages" data-toggle="collapse" class="collapsed"><i class="glyphicon glyphicon-globe"></i> <span>数据中心信息</span>
            <i class="icon-submenu lnr lnr-chevron-left"></i></a>
        <div id="subPages" class="collapse ">
            <ul class="nav">
                {% for dcinfo in dc_obj %}
                    <li>
                        <a href="#{{ dcinfo.name }}" data-toggle="collapse" class="collapsed"><i
                                class="glyphicon glyphicon-home"></i> <span>{{ dcinfo.name }}</span> <i
                                class="icon-submenu lnr lnr-chevron-left"></i></a>
                        <div id="{{ dcinfo.name }}" class="collapse ">
                            <ul class="nav">

                                {% for idcinfo in dcinfo.idcinfo_set.all %}
                                    <li>
                                        <a href="#{{ dcinfo.name }}{{ idcinfo.name }}" data-toggle="collapse"
                                           class="collapsed text-center">
                                            <i class="glyphicon glyphicon-cd"></i> <span>{{ idcinfo.name }}机房</span>
                                            <i class="icon-submenu lnr lnr-chevron-left"></i>
                                        </a>
                                        <div id="{{ dcinfo.name }}{{ idcinfo.name }}" class="collapse ">
                                            <ul class="nav">
                                                <li><a href="{% url 'dcinfo:get_cabinet'  dcinfo.name   idcinfo.name %}"
                                                       class="text-center"
                                                       id="cabinet-info{{ dcinfo.name }}{{ idcinfo.name }}">机柜管理</a>
                                                </li>
                                                <li><a href="{% url 'dcinfo:get_equipmen' dcinfo.name   idcinfo.name %}"
                                                       class="text-center"
                                                       id="equipmen-info{{ dcinfo.name }}{{ idcinfo.name }}">设备管理</a>
                                                </li>
                                                <li><a href="{% url 'dcinfo:inventory' dcinfo.name   idcinfo.name %}"
                                                       class="text-center"
                                                       id="inventory-info{{ dcinfo.name }}{{ idcinfo.name }}">库存管理</a>
                                                </li>
                                                <li><a href="{% url 'dcinfo:get_abnormal' dcinfo.name idcinfo.name %}"
                                                       class="text-center"
                                                       id="abnormal-info{{ dcinfo.name }}{{ idcinfo.name }}">异常告警</a>
                                                </li>
                                            </ul>
                                        </div>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </li>

                {% endfor %}
            </ul>
        </div>
    </li>

    <li>
        <a href="#customer-menu" data-toggle="collapse" class="collapsed">
            <i class="glyphicon glyphicon-send"></i>
            <span>客户资产信息</span>
            <i class="icon-submenu lnr lnr-chevron-left"></i>
        </a>
        <div id="customer-menu" class="collapse ">
            <ul class="nav">
                {% for customer in customer_obj %}
                    <li>
                        <a href="{% url 'dcinfo:get_customer' customer.name %}" id="customet-{{ customer.name }}">
                            <i class="glyphicon glyphicon-user"></i>
                            <span>{{ customer.name }}</span>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </li>

    <li><a href="/xadmin" class=""><i class="lnr lnr-linearicons"></i> <span>后台管理</span></a></li>
{% endblock menu_list %}


{% block context %}
    {% block aphorism %}{% endblock aphorism %}
    <div class="panel panel-headline">

        <div class="panel-body">
            {% block panel-body %}

                {#    数据统计部分#}
                <div class="row">
                    <div class="col-md-3">
                        <div class="metric">
                            <span class="icon"><i class="glyphicon glyphicon-stats"></i></span>
                            <p>
                                <span class="number">{{ customer_obj.count }}</span>
                                <span class="title">客户数量</span>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="metric">
                            <span class="icon"><i class="glyphicon glyphicon-stats"></i></span>
                            <p>
                                <span class="number">{{ dc_obj.idc_count }}</span>
                                <span class="title">机房数量</span>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="metric">
                            <span class="icon"><i class="glyphicon glyphicon-stats"></i></span>
                            <p>
                                <span class="number">{{ dc_obj.cabinet_count }}</span>
                                <span class="title">机柜数量</span>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="metric">
                            <span class="icon"><i class="glyphicon glyphicon-stats"></i></span>
                            <p>
                                <span class="number">{{ dc_obj.equipment_count }}</span>
                                <span class="title">设备数量</span>
                            </p>
                        </div>
                    </div>

                </div>

                {#    统计图部分#}
                <br>
                <div class="row">
                    {#            机柜增减统计图#}
                    <div class="col-md-7">
                        <div id="cablein-count" style="width: 100%; height: 400px"></div>
                    </div>
                    {#            机房机柜数量圆形统计图#}
                    <div class="col-md-5">
                        <div id="idc-count" style="width: 100%; height: 400px"></div>
                    </div>
                </div>
            {% endblock panel-body %}
        </div>
    </div>

{% endblock context %}

{#数据统计#}
{#    日志部分#}
{% block log %}
    {#    客户机柜日志#}
    <div class="row">
        {#        客户机柜日志#}
        <div class="col-md-6">
            <div class="panel">
                <div class="panel-heading">
                    <h3 class="panel-title">客户机柜日志</h3>
                    <div class="right">
                        <button type="button" class="btn-toggle-collapse"><i class="lnr lnr-chevron-up"></i></button>
                        <button type="button" class="btn-remove"><i class="lnr lnr-cross"></i></button>
                    </div>
                </div>
                <div class="panel-body no-padding" style="height: 473px; overflow: hidden">
                    <iframe src="{% url 'dcinfo:customer_cabinet_log' %}" frameborder="0"
                            style="width: 100%; height: 473px" scrolling="no"></iframe>
                </div>
            </div>

        </div>
        {#        客户机柜数量统计图#}
        <div class="col-md-6">
            <div class="panel">
                <div class="panel-heading">
                    <h3 class="panel-title">客户机柜数量统计图</h3>
                    <div class="right">
                        <button type="button" class="btn-toggle-collapse"><i class="lnr lnr-chevron-up"></i></button>
                        <button type="button" class="btn-remove"><i class="lnr lnr-cross"></i></button>
                    </div>
                </div>
                <div class="panel-body no-padding" style="height: 473px">
                    <div id="customet_caninet_count" style="width: 100%; height: 473px"></div>
                </div>
            </div>
        </div>
    </div>
    {#    服务器日志#}
    <div class="row">
        {#        客户服务器数量统计图#}
        <div class="col-md-5">
            <div class="panel">
                <div class="panel-heading">
                    <h3 class="panel-title">客户服务器数量统计图</h3>
                    <div class="right">
                        <button type="button" class="btn-toggle-collapse"><i class="lnr lnr-chevron-up"></i></button>
                        <button type="button" class="btn-remove"><i class="lnr lnr-cross"></i></button>
                    </div>
                </div>
                <div class="panel-body no-padding" style="height: 473px">
                    <div id="customet_equipment_count" style="width: 100%; height: 473px"></div>
                </div>
            </div>
        </div>
        {#        客户服务器日志#}
        <div class="col-md-7">
            <div class="panel">
                <div class="panel-heading">
                    <h3 class="panel-title">客户服务器日志</h3>
                    <div class="right">
                        <button type="button" class="btn-toggle-collapse"><i class="lnr lnr-chevron-up"></i></button>
                        <button type="button" class="btn-remove"><i class="lnr lnr-cross"></i></button>
                    </div>
                </div>
                <div class="panel-body no-padding" style="height: 473px; overflow: hidden">
                    <iframe src="{% url 'dcinfo:customer_equipmen_log' %}" frameborder="0"
                            style="width: 100%; height: 473px" scrolling="no"></iframe>
                </div>
            </div>
        </div>
    </div>
{% endblock log %}


{% block motai %}
    <!-- Button trigger modal -->

    <div class="modal fade " id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content ">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">{% block motai-title %}Modal
                        title{% endblock motai-title %}</h4>
                </div>
                <div class="modal-body">
                    {% block motai-body %}...{% endblock motai-body %}
                </div>
                <div class="modal-footer">
                    {% block motai-btn %}
                        <button type="button" class="btn btn-primary">Save changes</button>
                    {% endblock motai-btn %}
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                </div>
            </div>
        </div>
    </div>
{% endblock motai %}